language: python
python: 
 - "3.7"
before_install:
install:
 - pip install -r requirements.txt
before_script:
script:
 - pytest-notebook
after_success:
after_failure:
before_deploy:
deploy:
after_deploy: